<?php
    function hello_menu() {
        $items = array();
        $items['hello_user'] = array(
            'title' => "We have a new User!",
            'page callback' => 'new_user',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function new_user() {
        return '<p>We have a new user! Send them an email</p>';
    }
    
    function hello_user_insert() {
        $_GET['destination'] = 'hello_user';
    }
